name: Docker

on:
 workflow_call:

jobs:
  Docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name:  Docker Setup Buildx
      uses: docker/setup-buildx-action@v3.8.0
     
      
