name: Go

on:
  push:
   branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go_version: ['1.18', '1.17', '>=1.18']
        os: ['ubuntu-latest', 'ubuntu-18.04']
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go_version }
        
  build:
    - needs: test
        runs-on: ${{ matrix.os }}
        strategy:
          matrix:
            os: ['ubuntu-latest', 'ubuntu-18.04']
        steps:
          - uses: actions/checkout@v3
          - name: Build
            run: go build -v main.go
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Install Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose

    - name: Check Docker version
      run: docker --version

    - name: Check Docker Compose version
      run: docker-compose --version

    - name: Run Docker Compose
      run: docker-compose up -d

    
