name: CI

on:
  push:
    branches: ['*']
  pull_request:
    branches: ['*']

env:
  DOCKER_IMAGE_NAME: your-image-name
  GO_VERSION: '1.18, 1.17, >=1.18'

jobs:

  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go_version: ['1.18', '1.17', '>=1.18']
        os: ['ubuntu-latest', 'ubuntu-18.04']
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go_version }}
    - name: Build Docker image
      run: docker buildx build -t your-image-name .
    - name: Create-DB
      run: docker run -d your-image-name
    - name: Test
      run: go test -v main_test.go

  build:
    needs: test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-latest', 'ubuntu-18.04']
    steps:
    - uses: actions/checkout@v3
    - name: Build Docker image
      run: docker build -t ${{ env.DOCKER_IMAGE_NAME }}:${{ github.sha }} .
    - name: Build
      run: go build -v main.go
    - name: Publish Docker image
      run: |
        docker push ${{ env.DOCKER_IMAGE_NAME }}:${{ github.sha }}
